name: deploy-to-docker

on:
  release:
    types: [created]

jobs:
    deploy:
        name: Running docker intance on github
        runs-on: ubuntu-latest

        steps:
        - name: install ssh keys to ssh into oracle
          # check this thread to understand why its needed:
          # <https://stackoverflow.com/a/70447517>
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: connecting to oracle....pulling latest code...Reloading docker compose
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git pull -f && exit"
        - name: cleanup
          run: rm -rf ~/.ssh
